### PR TITLE
Update p256k1 version

### PR DESCRIPTION
**Pull request by aryzing**
Updates `p256k1` version. Depends on https://github.com/Trust-Machines/p256k1/pull/65

### CODE REVIEW

**Comment by xoloki** [comment]
p256k1 PR approved and merged, lmk when you're satisfied with this one

**Comment by xoloki** [comment]
Actually I'll need to publish a new crate first, I'll let you know when I'm back from the beach 😹

**Review by xoloki — APPROVED** [review]
LGTM

**Comment by xoloki** [comment]
Is there anything else you'd like to do in this PR @aryzing now that `p256k1` has been updated?

**Comment by aryzing** [comment]
> p256k1 has been updated

Thanks! This PR is good to go

**Pull request merged**
