### PR TITLE
Code coverage (from a local branch)

### PR DESCRIPTION
**Pull request by sergey-shandar**

### CODE REVIEW

**Comment by sergey-shandar** [comment]
@xoloki I can create a local branch in the repo (thank you!) but CI still doesn't run. I don't have access to settings. Would you like to switch on Actions for the repo?

**Comment by xoloki** [comment]
> @xoloki I can create a local branch in the repo (thank you!) but CI still doesn't run. I don't have access to settings. Would you like to switch on Actions for the repo?

I thought I'd turned that on already, lemme check

**Comment by sergey-shandar** [comment]
> > @xoloki I can create a local branch in the repo (thank you!) but CI still doesn't run. I don't have access to settings. Would you like to switch on Actions for the repo?
> 
> I thought I'd turned that on already, lemme check

I can see derived actions history from Frost but no WSTS actions.

**Comment by xoloki** [comment]
> > > @xoloki I can create a local branch in the repo (thank you!) but CI still doesn't run. I don't have access to settings. Would you like to switch on Actions for the repo?
> > 
> > 
> > I thought I'd turned that on already, lemme check
> 
> I can see derived actions history from Frost but no WSTS actions.

I'm confused, I see that `ci.yml` is running under Actions, with `check`, `test-all`, `fmt`, `clippy`, and `doc` actions running when pushing to branches.

What do you mean that there are "no WSTS actions"?

**Comment by xoloki** [comment]
Oh weird it's not running CI for this branch, lemme check on that.

**Comment by xoloki** [comment]
I don't see any obvious problems @sergey-shandar so I made you an admin :)

**Pull request closed without merging**
